apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: yurchenkopo/ml_project_app:v1
      name: fastapi-ml
      ports:
        - containerPort: 8000
