apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-health
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: yurchenkopo/ml_project_app:v4
      name: fastapi-ml
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /healz
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 3