apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-resources
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: yurchenkopo/ml_project_app:v1
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "10Gi"
          cpu: "500m"